### ISSUE TITLE
Connect it to Parse.com

### ISSUE THREAD

**Issue by lorencogonzaga** [fullc0de/HKKTagWriteView#4]
Hi buddy!
First excellent code and example!

It would be nice if the tags were linked to a backend, like Parse.com for example.
Any chance you update this example to do this or could provide any directions on how to update this to Parse ?

Thnx and cheers!

**Comment by lorencogonzaga** [comment]
Ok I manage to connect it to Parse. I would try now load the tags from Parse to the TagWriteView.

I did it setting a column to my Object in Parse backend called tags of type Array.
Then in the view controller where it loads the _tagWriteView I deleted the line
[_tagWriteView addTags:@[@"sample tags]];

And in my method to Parse I linked _tagWriteView to tags instead of addTags(above)

PFObject *newObeject = [PFObject objectWithClassName:@"yourClassName"];
[newObject setObject:[_tagWriteView tags] forKey:@"tags"];

**Comment by fullc0de** [comment]
Hello @lorencogonzaga .  I apologize you for late anwser. At first, I don't have any experiences of Parse. So, I am sorry that I don't give you any idea about linking TagWriteView to Parse. 

I am sure that you can make TagWriteView more useful by linking to Parse. Could you give me a pull request after finishing your work?

**Comment by lorencogonzaga** [comment]
Hi @fullc0de, thnx for the reply

I already had success linking it to Parse, I will post a link with a complete project and share here.

Now I need to configure the tags to pull the stored tag values from Parse.

Cheers!

**Comment by fullc0de** [comment]
@lorencogonzaga 
I looked for what Parse is. It looked amazing cloud platform. 
I appreciate you knowing about Parse. I hope that your work would end up being successful.

**Comment by lorencogonzaga** [comment]
Hi buddy! 

Yeah, Parse is really cool plataform, the best I think. Relatively easy to start working with. I hope to succeed with my project too, thnx! But succesful or not I will definetly write thanks to you and l the others that somehow help!

Cheers!
