### ISSUE TITLE
Is it possible to add HKTagWriteView into a swift project?

### ISSUE THREAD

**Issue by liuslevis** [fullc0de/HKKTagWriteView#6]
Hoping for your reply, thanks.

**Comment by liuslevis** [comment]
class MainViewController: TagWriteViewDelegate {
    @IBOutlet var tagView: TagWriteView?
    override func viewDidLoad() {
        // MARK: Init TagView
        self.tagView = TagWriteView(frame:CGRectMake(0, 64, 100, 50))
        //        self.tagView.tagBackgroundColor
        self.tagView!.backgroundColor = UIColor.blackColor()
        self.tagView!.delegate = self
        self.tagView!.allowToUseSingleSpace = true
        self.tagView!.addTags(["one","tow","String A", "String B"])
        self.view.addSubview(tagView!)
    }
}

would be the solution

**Comment by fullc0de** [comment]
I'm not sure if I understand your question or not, but swift version of the view is contained in the project. You can find `TagWriteView.swift` file on TagWriteViewTest directory.
